package pt.karimp.bem_vindo.models

import android.R

data class Frase(
    val frase: List<String> = emptyList<String>(),
    val frase1Fr: String = "",
    val frase1: String = "",
    val frase1En: String = "",
    val frase1Es: String = "",
    val frase2Fr: String = "",
    val frase2: String = "",
    val frase2En: String = "",
    val frase2Es: String = "",
    val frase3Fr: String = "",
    val frase3: String = "",
    val frase3En: String = "",
    val frase3Es: String = "",
    val frase4Fr: String = "",
    val frase4: String = "",
    val frase4En: String = "",
    val frase4Es: String = "",
    val frase5Fr: String = "",
    val frase5: String = "",
    val frase5En: String = "",
    val frase5Es: String = "",
    val frase6Fr: String = "",
    val frase6: String = "",
    val frase6En: String = "",
    val frase6Es: String = "",
    val frase7Fr: String = "",
    val frase7: String = "",
    val frase7En: String = "",
    val frase7Es: String = "",
    val frase8Fr: String = "",
    val frase8: String = "",
    val frase8En: String = "",
    val frase8Es: String = "",
    val frase9Fr: String = "",
    val frase9: String = "",
    val frase9En: String = "",
    val frase9Es: String = "",
    val frase10Fr: String = "",
    val frase10: String = "",
    val frase10En: String = "",
    val frase10Es: String = "",
)